components {
  id: "WorldElement"
  component: "/Placeables/Common/S_WorldElement.script"
}
components {
  id: "SaveObject"
  component: "/Placeables/SaveObjects/S_SaveObject.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"SleepingBag\"\n"
  "material: \"/Core/Materials/M_OutlineSprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/Art/Placeables/ATL_Placeable.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "trigger"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"trigger\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: -2.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 18.0\n"
  "  data: 12.5\n"
  "  data: 8.0\n"
  "}\n"
  ""
}
