go.property("obstacleGroup", 0)

function init(self)
    msg.post(go.get_parent(go.get_id()), "RegisterObstacle", {group = self.obstacleGroup})
end

function on_message(self, message_id, message, sender)
    if message_id == hash("SetCollision") then
        physics.set_group("#collision", (message.collision and "wall" or "player"))
        local z = message.collision and 0.45 or -50
        local pos = go.get_position()
        pos.z = z
        go.set_position(pos)
    end
end